# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jake/code/emu/z80

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jake/code/emu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jake/code/emu/CMakeFiles /home/jake/code/emu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jake/code/emu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reset

# Build rule for target.
reset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reset
.PHONY : reset

# fast build rule for target.
reset/fast:
	$(MAKE) -f tests/CMakeFiles/reset.dir/build.make tests/CMakeFiles/reset.dir/build
.PHONY : reset/fast

#=============================================================================
# Target rules for targets named interrupts

# Build rule for target.
interrupts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interrupts
.PHONY : interrupts

# fast build rule for target.
interrupts/fast:
	$(MAKE) -f tests/CMakeFiles/interrupts.dir/build.make tests/CMakeFiles/interrupts.dir/build
.PHONY : interrupts/fast

#=============================================================================
# Target rules for targets named dummy_state

# Build rule for target.
dummy_state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dummy_state
.PHONY : dummy_state

# fast build rule for target.
dummy_state/fast:
	$(MAKE) -f tests/CMakeFiles/dummy_state.dir/build.make tests/CMakeFiles/dummy_state.dir/build
.PHONY : dummy_state/fast

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f tests/CMakeFiles/tester.dir/build.make tests/CMakeFiles/tester.dir/build
.PHONY : tester/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) -f examples/CMakeFiles/examples.dir/build.make examples/CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named input_and_output

# Build rule for target.
input_and_output: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 input_and_output
.PHONY : input_and_output

# fast build rule for target.
input_and_output/fast:
	$(MAKE) -f examples/CMakeFiles/input_and_output.dir/build.make examples/CMakeFiles/input_and_output.dir/build
.PHONY : input_and_output/fast

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) -f examples/CMakeFiles/hello.dir/build.make examples/CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named custom_state

# Build rule for target.
custom_state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom_state
.PHONY : custom_state

# fast build rule for target.
custom_state/fast:
	$(MAKE) -f examples/CMakeFiles/custom_state.dir/build.make examples/CMakeFiles/custom_state.dir/build
.PHONY : custom_state/fast

#=============================================================================
# Target rules for targets named assembly_review

# Build rule for target.
assembly_review: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembly_review
.PHONY : assembly_review

# fast build rule for target.
assembly_review/fast:
	$(MAKE) -f examples/CMakeFiles/assembly_review.dir/build.make examples/CMakeFiles/assembly_review.dir/build
.PHONY : assembly_review/fast

#=============================================================================
# Target rules for targets named adding_memory

# Build rule for target.
adding_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adding_memory
.PHONY : adding_memory

# fast build rule for target.
adding_memory/fast:
	$(MAKE) -f examples/CMakeFiles/adding_memory.dir/build.make examples/CMakeFiles/adding_memory.dir/build
.PHONY : adding_memory/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f examples/CMakeFiles/benchmark.dir/build.make examples/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named accessing_state

# Build rule for target.
accessing_state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 accessing_state
.PHONY : accessing_state

# fast build rule for target.
accessing_state/fast:
	$(MAKE) -f examples/CMakeFiles/accessing_state.dir/build.make examples/CMakeFiles/accessing_state.dir/build
.PHONY : accessing_state/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... reset"
	@echo "... interrupts"
	@echo "... dummy_state"
	@echo "... tester"
	@echo "... examples"
	@echo "... input_and_output"
	@echo "... hello"
	@echo "... custom_state"
	@echo "... assembly_review"
	@echo "... adding_memory"
	@echo "... benchmark"
	@echo "... accessing_state"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

