#define VIDEO_ADDR_STATE 0x00
#define VIDEO_ADDR_MODE 0x01
#define VIDEO_ADDR_IN 0x02
#define VIDEO_ADDR_OUT 0x03
#define VIDEO_ADDR_TOF 0x04

#define VIDEO_MODE_CLEAR 0x00
#define VIDEO_MODE_PLOT  0x01
#define VIDEO_MODE_LINE  0x02

#define VIDEO_MODE_LOAD_IMAGE  0x99 // VIDEO_ADDR_OUT will contain an image id
#define VIDEO_MODE_FREE_IMAGE  0x99 // VIDEO_ADDR_OUT will contain an image id
#define VIDEO_MODE_BLIT_IMAGE  0x99

#define VIDEO_MODE_TILESHEET_SET_ACTIVE  0x30
#define VIDEO_MODE_TILESHEET_LOAD  0x31
#define VIDEO_MODE_TILESHEET_FREE  0x32
#define VIDEO_MODE_TILESHEET_BLIT_TILE  0x33


#define VIDEO_STATE_READY 0x00
#define VIDEO_STATE_BUSY 0x01
#define VIDEO_STATE_RCV_X_UPPER 0x02
#define VIDEO_STATE_RCV_X_LOWER 0x03
#define VIDEO_STATE_RCV_Y_UPPER 0x04
#define VIDEO_STATE_RCV_Y_LOWER 0x05
#define VIDEO_STATE_RCV_COLOR 0x06
#define VIDEO_STATE_RCV_TILESHEET_ID 0x30
#define VIDEO_STATE_RCV_TILE_ID 0x31
