#define VIDEO_ADDR_STATE 0x00
#define VIDEO_ADDR_MODE 0x01
#define VIDEO_ADDR_IN 0x02
#define VIDEO_ADDR_META 0x03
#define VIDEO_ADDR_TOF 0x04

#define VIDEO_MODE_CLEAR 0x00
#define VIDEO_MODE_PLOT  0x01

#define VIDEO_STATE_READY 0x00
#define VIDEO_STATE_BUSY 0x01
#define VIDEO_STATE_RCV_X_UPPER 0x02
#define VIDEO_STATE_RCV_X_LOWER 0x03
#define VIDEO_STATE_RCV_Y_UPPER 0x04
#define VIDEO_STATE_RCV_Y_LOWER 0x05
#define VIDEO_STATE_RCV_COLOR 0x06